# Generated by Django 2.1.5 on 2019-02-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkSpot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spots',
            name='spot',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.TextField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Spots',
        ),
    ]
