# Generated by Django 2.1.5 on 2019-02-22 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkSpot_app', '0002_auto_20190222_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parkSpot_app.User')),
            ],
        ),
    ]
