# Generated by Django 2.1.5 on 2019-02-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkSpot_app', '0005_auto_20190227_0518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spots',
            new_name='SpotList',
        ),
        migrations.RenameField(
            model_name='spotlist',
            old_name='spot',
            new_name='spots',
        ),
    ]
